version: 2
jobs:
  cypress/run:
    docker:
      - image: cypress/base:10
    parallelism: 1
    steps:
    - checkout
    - run:
        name: yarn install
        command: yarn install
    - run:
        command: npx cypress verify
    - persist_to_workspace:
        root: ~/
        paths:
        - project
        - .cache/Cypress
    - run:
        name: Run Cypress tests
        command: "npm run test"
    - store_artifacts:
        path: cypress/videos
    - store_artifacts:
        path: cypress/screenshots
workflows:
  build:
    jobs:
    - cypress/run
  version: 2